# Generated by Django 5.1.3 on 2024-12-04 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargaXLS', '0002_datarow_delete_archivoxls'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColumnClassification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('columna_nombre', models.CharField(max_length=255)),
                ('tipo_dato', models.CharField(choices=[('numerica', 'Numérica'), ('categorica', 'Categórica')], max_length=50)),
                ('archivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columnas', to='cargaXLS.datarow')),
            ],
        ),
    ]
