# Generated by Django 5.1.3 on 2024-12-06 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargaXLS', '0003_columnclassification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='columnclassification',
            name='tipo_dato',
            field=models.CharField(choices=[('real', 'Real'), ('categorico', 'Categórico'), ('entero', 'Entero')], max_length=50),
        ),
        migrations.AlterField(
            model_name='datarow',
            name='archivo_nombre',
            field=models.CharField(max_length=255),
        ),
    ]
