# Generated by Django 5.1.3 on 2024-12-10 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargaXLS', '0004_alter_columnclassification_tipo_dato_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeloEstandarizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_archivo', models.CharField(max_length=255)),
                ('data', models.JSONField()),
            ],
        ),
    ]
